-- Module      : Deer.Definitions
-- Description : Definitions of relation representations, mappings between, etc.
-- Copyright   : (c) Lulof Pirée, 2026
-- License     : AGPL-v3
-- Maintainer  : Lulof Pirée
-- Stability   : experimental
--------------------------------------------------------------------------------
open import Level
open import Data.Bool hiding (_≤_)
open import Data.Nat
open import Relation.Binary
open import Relation.Binary.Definitions
open import Relation.Binary.PropositionalEquality
open import Data.Product
open import Relation.Binary.Structures

--open import Relation.Nullary
--open ≡-Reasoning
--open import Data.Nat.Properties
--open import Data.Sum
--open import Data.Fin
--open import Data.Fin.Properties
--open import Data.Fin.Induction
--open import Data.Unit
--open import Data.Empty
--open import Data.List
--open import Data.List.Relation.Unary.AllPairs using (AllPairs)
--open import Data.List.Relation.Unary.All using (All)
--open import Data.List.Relation.Binary.Suffix.Heterogeneous using (Suffix)
--open import Data.List.Membership.Propositional using (_∈_ ; _∉_ )
--open import Data.List.Membership.Propositional.Properties using (∈-lookup)
--open import Data.List.Relation.Unary.Any using (Any)

module Deer.Definitions where

--------------------------------------------------------------------------------
-- Relations on ℕ
--------------------------------------------------------------------------------

-- Relations as functions. 
-- This Bool-valued representation is always proof-irrelevant
-- and decidable, and more convenient when proving homotopy between relations.
-- The Agda stdlib lets a relation output a Set, which is annoying when
-- trying to show a homotopy that does not care about proof implementations.
-- See below `_ ⊢ _ ~ _` for a conversion to the stdlib's representation.
DecRel : Set
DecRel = ℕ → ℕ → Bool

_⊢_~_ : DecRel → Rel ℕ 0ℓ
R ⊢ n ~ m = R n m ≡ true

-- Decidable equivalence relations.
DecEquiv : Set
DecEquiv = Σ[ R ∈ DecRel ]( IsEquivalence (R ⊢_~_) )

-- Proposition on a relation (property of a relation).
RelProp : Set
RelProp = DecRel → Bool

-- Predicate that a relation satisfies a proposition (i.e. has a property).
sat : DecRel → RelProp → Set
sat R P = P R ≡ true

-- Equivalence relations that also satisfy proposition P.
DecEquivThatSats : RelProp → Set
DecEquivThatSats P = Σ[ R ∈ DecRel ] (IsEquivalence (R ⊢_~_) × sat R P)

--------------------------------------------------------------------------------
-- Equivalence-Classes graphs and piecewise extensions thereof
--------------------------------------------------------------------------------
-- Class graphs without any coherence conditions.
IncohClassGraph = (n : ℕ) (vec n ℕ) × ℕ

-- Class graphs generated by g : ℕ → ℕ
-- such that g : n ↦ ([g 0, g 1, ... g (n-1)] , g n)
ChoiceHist = Σ[ g ∈ IncohClassGraph ] (IsCoherent g)




--------------------------------------------------------------------------------
-- Normal-form functions
--------------------------------------------------------------------------------

-- Coherence constraint on normal form functions: 
-- the normal form of n is always smaller or equal to n,
-- i.e., has been explored earlier.
-- This is necessary when building equivalence relations by inductively
-- assigning each n ∈ ℕ to its normal form.
NLeq : (ℕ → ℕ) → Set
NLeq f = (n : ℕ) → f n ≤ n

-- Coherence constraint on normal form functions: 
-- the normal form of a normal form is itself.
NFix : (ℕ → ℕ) → Set
NFix f = (n : ℕ) → f (f n) ≡ f n

NFFun : Set
NFFun = Σ[ f ∈ (ℕ → ℕ) ]( NLeq f × NFix f)
